[MI-3058] Fix issue 95 of syncing mentions in the channels and chat
mattermost/mattermost-plugin-msteams-sync pull request #111
Opened 2023-05-08 08:14 UTC by ayusht2810

#### Summary
Fixed the issue of syncing user mentions and special mentions from MS teams to Mattermost and from Mattermost to MS teams.

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/95

2023-05-11 17:42 UTC, jespino commented on server/msteams/client.go
> +			mmUser, err := tc.plugin.GetUserByUsername(username)
I have concerns about having to pass the whole API and the whole store to address this. That leads me to think that  it is not responsability of the client calculate the list of mentions. Maybe it should be done outside somehow.

2023-05-11 17:45 UTC, jespino requested changes
The main problem that i see in this code is we are introducing a big coupling here unless you have a clear vision that this should be part of the client, I would move that outside, probably as part of the package that calls it.

If you feel really strong about having it here, at least, I would encapsulate that in a function that you pass to the client, instead of passing the whole API and the whole store.

2023-05-12 10:11 UTC, ayusht2810 commented
@jespino fixed the review comment. Please re-review

2023-05-17 11:26 UTC, jespino approved these changes
LGTM

2023-05-17 11:27 UTC, merged