Fix issue 106 by adding developer docs
mattermost/mattermost-plugin-msteams-sync pull request #114
Opened 2023-05-09 07:11 UTC by ayusht2810

#### Summary
Added developer docs in the Readme

#### Ticket Link
#106

2023-05-11 14:55 UTC, jespino commented on docs/developer_docs.md
> +    - If the setting "Enforce connected accounts" is enabled in the plugin's config settings, then a full screen modal appears that looks like this -
Same here

2023-05-11 14:55 UTC, jespino commented on docs/developer_docs.md
> +    - Run the slash command `/msteams-sync connect-bot` in any channel.
Same here

2023-05-11 14:56 UTC, jespino requested changes
There are some information that is out of date after the last changes in authentication and the client library. Other than that it looks good to me.

2023-05-12 16:52 UTC, ayusht2810 commented
@jespino did the review fixes. Please re-review

2023-05-17 11:24 UTC, jespino approved these changes
LGTM

2023-05-17 11:24 UTC, merged