[MI-3288] Add content-type header in different events
mattermost/mattermost-plugin-msteams-sync pull request #214
Opened 2023-07-12 14:50 UTC by ayusht2810

#### Summary
Add content-type header in different events

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/213

2023-07-17 15:50 UTC, esarafianou approved these changes

2023-07-18 07:59 UTC, manojmalik20 commented
Are we sure that setting the conent type in response will save us from attacks? @esarafianou @jespino

2023-07-24 11:34 UTC, jespino requested changes
Actually the real content type there is `plain/text`, not `application/json`

2023-07-24 14:14 UTC, jespino approved these changes

2023-07-24 14:15 UTC, ayusht2810 commented
@jespino updated the content-type. Please re-review

2023-07-26 09:20 UTC, jespino commented
@ayusht2810 looks like the CI is failing without a reason, can you take a look, maybe we need to merge the main branch or something like that.

2023-08-09 11:37 UTC, manojmalik20 approved these changes

2023-08-09 11:37 UTC, manojmalik20 commented on server/store/store_test.go
> +		conn, _ := sqlx.Connect("postgres", fmt.Sprintf("postgres://user:pass@%s:%d?sslmode=disable", host, hostPort.Int()))
```suggestion
		conn, _ := sqlx.Connect(driverName, fmt.Sprintf("postgres://user:pass@%s:%d?sslmode=disable", host, hostPort.Int()))
```

2023-08-09 12:47 UTC, merged