[MI-3286] Create an RHS state to connect user account and show different states for linked channels
mattermost/mattermost-plugin-msteams-sync pull request #229
Opened 2023-07-31 08:15 UTC by ayusht2810

#### Summary

- Added a button for users to connect to MS Teams.
- Added different RHS states for showing linked channels.

![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/6e4409cd-1862-48cd-a0eb-9a6ffb4c92ad)
![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/bf61720a-1508-45fe-8b55-499ce74ec5a2)

2023-08-09 09:16 UTC, raghavaggarwal2308 requested changes

2023-08-09 09:16 UTC, raghavaggarwal2308 commented on webapp/src/types/module.d.ts
Just a question. What is the use of this file?

2023-08-09 12:56 UTC, ayusht2810 commented on server/api.go
> +		"connect",
discussed

2023-08-09 12:57 UTC, ayusht2810 commented on webapp/src/app.tsx
> +    return <></>;
discussed

2023-08-09 12:58 UTC, ayusht2810 commented on webapp/src/containers/Rhs/rhs.scss
> +    position: absolute;
it is removed in the next PR https://github.com/mattermost/mattermost-plugin-msteams-sync/blob/c41e673b6b1f3226296e435288863660a6ef8649/webapp/src/containers/Rhs/rhs.scss#L165

2023-08-09 12:59 UTC, ayusht2810 commented on webapp/src/types/module.d.ts
this file is used to define the types present in the package

2023-08-11 15:17 UTC, raghavaggarwal2308 approved these changes

2023-11-23 09:09 UTC, ayusht2810 commented
Closing this PR in favour of updated [figma designs](https://www.figma.com/file/aRgXgPZQ3lDaow5uatDzz9/MS-Teams-Sync-RHS?type=design&node-id=1-7&mode=design&t=ewtCZk3sFs0sMBLl-0). We will pick changes from this PR if required.

2023-11-23 09:09 UTC, closed without merging