[MI-3321] Post a DM message on the successful connection of the user with MS Teams
mattermost/mattermost-plugin-msteams-sync pull request #230
Opened 2023-07-31 08:28 UTC by ayusht2810

#### Summary
Post a DM message on the successful connection of the user with MS Teams.
![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/229fd04a-215a-43f6-ae0e-c7f414f3bd89)

2023-08-09 09:21 UTC, raghavaggarwal2308 requested changes

2023-08-09 09:21 UTC, raghavaggarwal2308 commented on server/api.go
> +	_, _ = a.p.DM(mmUserID, "You've successfully connected your Mattermost account to MS Teams.")
Check error

2023-08-10 07:28 UTC, ayusht2810 commented on server/bot.go
> +// DM posts a simple Direct Message to the specified user
I think it is already fine like this

2023-08-11 15:19 UTC, raghavaggarwal2308 approved these changes

2023-11-15 09:47 UTC, manojmalik20 approved these changes

2023-11-20 21:34 UTC, lieut-data commented
@ayusht2810 / @johndavidlugtu, can you confirm this is still a product requirement? I'm guessing it comes out of a flow where the user connects not via the slash command but via the RHS or some other UI?

2023-11-21 11:09 UTC, ayusht2810 commented
@lieut-data I think we can close this and other UI related PRs now, as the [figma designs](https://www.figma.com/file/aRgXgPZQ3lDaow5uatDzz9/MS-Teams-Sync-RHS?type=design&node-id=1-7&mode=design&t=ewtCZk3sFs0sMBLl-0) for the RHS is updated now.

2023-11-21 13:27 UTC, lieut-data commented
Thanks, @ayusht2810! Please do feel free to close any PRs that are no longer applicable especially if requirements have changed.

2023-11-23 09:02 UTC, ayusht2810 commented
closing this PR in favour of updated [figma designs](https://www.figma.com/file/aRgXgPZQ3lDaow5uatDzz9/MS-Teams-Sync-RHS?type=design&node-id=1-7&mode=design&t=ewtCZk3sFs0sMBLl-0)

2023-11-23 09:02 UTC, closed without merging