[MI-3475] Add feature to unlink linked channels
mattermost/mattermost-plugin-msteams-sync pull request #284
Opened 2023-09-04 04:54 UTC by ayusht2810

#### Summary
Add feature to unlink linked channels

2023-10-10 15:36 UTC, raghavaggarwal2308 requested changes
Fix CI

2023-10-10 15:36 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/index.tsx
> +                primaryActionText={showDestructivetDialog && primaryActionText}
```suggestion
                primaryActionText={showDestructiveDialog && primaryActionText}
```

2023-10-10 15:36 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/index.tsx
> +                                setPrimaryActionText('Disconnect');
Constants for 'Unlink' and 'Disconnect' as they are being used at multiple places

2023-11-23 09:06 UTC, ayusht2810 commented
Closing this PR in favour of updated [figma designs](https://www.figma.com/file/aRgXgPZQ3lDaow5uatDzz9/MS-Teams-Sync-RHS?type=design&node-id=1-7&mode=design&t=ewtCZk3sFs0sMBLl-0). We will pick changes from this PR if required.

2023-11-23 09:06 UTC, closed without merging