[MI-3591] Add transactions in the functions to avoid race conditions
mattermost/mattermost-plugin-msteams-sync pull request #340
Opened 2023-10-10 08:40 UTC by ayusht2810

#### Summary
Add transactions in the functions to avoid race conditions

#### Ticket Link
#327 
#330

2023-10-11 09:10 UTC, raghavaggarwal2308 requested changes

2023-10-11 09:10 UTC, raghavaggarwal2308 commented on server/command_test.go
> +				s.On("CommitTx", &sql.Tx{}).Return(nil).Times(1)
Add testcases for errors as well

2023-10-11 09:10 UTC, raghavaggarwal2308 commented on server/monitor/subscriptions.go
> +			// m.client.DeleteSubscription(msteamsSubscription.ID)
need of this?

2023-10-11 09:10 UTC, raghavaggarwal2308 commented on server/store/store.go
> +	return nil
```suggestion
	_, err := query.Exec();
        return err
```
maybe?

2023-10-11 12:45 UTC, raghavaggarwal2308 approved these changes

2023-10-12 10:06 UTC, ayusht2810 commented on server/command_test.go
> +				}).Return(testutils.GetPost(testutils.GetChannelID(), testutils.GetUserID(), time.Now().UnixMicro())).Times(1)
discussed

2023-10-12 10:06 UTC, ayusht2810 commented on server/message_hooks.go
> +		teamsMessage, txErr = client.SetChatReaction(chatID, teamsMessageID, srcUserID, emoji.Parse(":"+emojiName+":"))
discussed

2023-10-12 10:07 UTC, ayusht2810 commented on server/message_hooks_test.go
> +				store.On("GetPostInfoByMattermostID", testutils.GetID()).Return(&storemodels.PostInfo{}, nil).Times(1)
discussed

2023-10-12 12:17 UTC, Kshitij-Katiyar commented on server/message_hooks.go
> +	if txErr = p.store.LinkPosts(storemodels.PostInfo{MattermostID: newPost.Id, MSTeamsChannel: channelID, MSTeamsID: postInfo.MSTeamsID, MSTeamsLastUpdateAt: updatedMessage.LastUpdateAt}, tx); txErr !=
Why we are not returning the error here.

2023-10-12 12:17 UTC, Kshitij-Katiyar commented on server/monitor/subscriptions_test.go
>  	} {
The name of the test case should TestRecreateChannelSubscription

2023-10-12 12:17 UTC, Kshitij-Katiyar commented on server/msteams/client.go
> +		return nil, errors.New("nil updateMessageRequest")
Please write user friendly error message

2023-10-12 12:17 UTC, Kshitij-Katiyar commented on server/msteams/client.go
> +		return nil, errors.New("nil updateMessageRequest")
Or descriptive log message

2023-10-12 13:24 UTC, Kshitij-Katiyar approved these changes

2023-10-12 13:24 UTC, Kshitij-Katiyar commented on server/msteams/client.go
> +		return nil, errors.New("Received nil updateMessageRequest from MS Graph")
Received nil in updateMessageRequest from MS Graph. Please change this everywhere

2023-10-12 15:22 UTC, closed without merging

2023-10-12 15:24 UTC, manojmalik20 approved these changes