[MI-3643] Add metrics to show messages confirmed count
mattermost/mattermost-plugin-msteams-sync pull request #356
Opened 2023-10-18 12:17 UTC by ayusht2810

#### Summary
- Add metrics to show messages confirmed count
- Fixed unit test cases

2023-10-23 09:39 UTC, Kshitij-Katiyar approved these changes

2023-10-23 10:11 UTC, ayusht2810 commented on server/metrics/metrics.go
> +		Name:        "messages_confirmed",
same https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/355#discussion_r1368384826

2023-10-23 17:29 UTC, lieut-data requested changes
Thanks again, @ayusht2810!

2023-10-23 17:29 UTC, lieut-data commented on server/handlers/handlers.go
> +	ActionSourceMattermost = "mattermost"
This doesn't feel like a constant that `handlers` should define. Can we export this from `metrics` instead?

2023-10-23 17:29 UTC, lieut-data commented on server/metrics/metrics.go
> +		Name:        "messages_confirmed",
Can we append `_total` as a suffix? I missed this in the original design document.

2023-10-24 14:02 UTC, manojmalik20 approved these changes

2023-10-24 14:27 UTC, lieut-data approved these changes

2023-10-25 05:45 UTC, merged