[MI-3768] Fixed the issue of headings not working properly from MS Teams to MM
mattermost/mattermost-plugin-msteams-sync pull request #415
Opened 2023-11-23 16:22 UTC by manojmalik20

#### Summary
Fixed the issue of headings not working properly from MS Teams to MM

#### Ticket Link
Fixes #393

2023-11-24 08:48 UTC, ayusht2810 approved these changes

2023-11-24 14:31 UTC, lieut-data requested changes

2023-11-24 14:31 UTC, lieut-data commented on server/markdown/markdown.go
> +	"<h3>",
Thanks, @manojmalik20! Are there unit tests we can update to add coverage here?

2023-11-24 18:03 UTC, lieut-data approved these changes
Thanks @manojmalik20!

2023-11-27 07:17 UTC, ayusht2810 approved these changes

2023-11-28 07:40 UTC, AayushChaudhary0001 approved these changes
Tested and approved. Working fine for all the heading types, LGTM.

2023-11-28 07:55 UTC, merged